# Generated by Django 6.0.3 on 2026-03-11 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursiones', '0003_add_sample_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursion',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
