# Generated by Django 6.0.3 on 2026-03-11 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursiones', '0004_alter_excursion_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursion',
            name='departure_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='excursion',
            name='group_size',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='excursion',
            name='itinerary',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='excursion',
            name='month',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='excursion',
            name='not_includes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='excursion',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='excursion',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
