# Generated by Django 6.0.3 on 2026-04-16 21:59

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excursiones', '0006_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursion',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
