# Generated by Django 6.0.3 on 2026-04-16 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursiones', '0006_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Vicente Viajes/excursiones/'),
        ),
    ]
