# Generated by Django 6.0.3 on 2026-04-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursiones', '0007_alter_excursion_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='Vicente Viajes/Usuarios/'),
        ),
    ]
