# Generated by Django 6.0.3 on 2026-05-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursiones', '0009_userprofile_must_change_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Vicente Viajes/excursiones/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='Vicente Viajes/Usuarios/'),
        ),
    ]
