"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""


from pathlib import Path
import os
from urllib.parse import parse_qs, unquote, urlparse
import cloudinary_storage
# Cargar variables de entorno desde .env explícitamente
from dotenv import load_dotenv
load_dotenv(dotenv_path=Path(__file__).resolve().parent.parent / '.env')

# Build paths inside the project like this: BASE_DIR / 'subdir'.
import cloudinary

# Cloudinary
BASE_DIR = Path(__file__).resolve().parent.parent


def _env_to_bool(raw_input, default=False):
    raw_value = str(raw_input if raw_input is not None else default).strip().lower()
    return raw_value in {'1', 'true', 'yes', 'on'}


def _split_csv_env(raw_value):
    return [item.strip() for item in str(raw_value or '').split(',') if item.strip()]


def _build_sqlite_database_config():
    return {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }


def _build_database_config_from_url(database_url_value):
    parsed = urlparse(database_url_value)
    scheme = parsed.scheme.lower()

    if scheme in {'sqlite', 'sqlite3'}:
        raw_path = unquote(parsed.path or '')
        if database_url_value.endswith(':memory:'):
            sqlite_name = ':memory:'
        else:
            sqlite_name = raw_path.lstrip('/') or str(BASE_DIR / 'db.sqlite3')
        return {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': sqlite_name,
        }

    if scheme not in {'postgres', 'postgresql', 'pgsql'}:
        raise ValueError(f'DATABASE_URL scheme no soportado: {scheme}')

    config = {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': unquote(parsed.path.lstrip('/')),
        'USER': unquote(parsed.username or ''),
        'PASSWORD': unquote(parsed.password or ''),
        'HOST': parsed.hostname or '',
        'PORT': str(parsed.port or '5432'),
    }

    query = parse_qs(parsed.query)
    options = {}
    sslmode = query.get('sslmode', [None])[0]
    if sslmode:
        options['sslmode'] = sslmode
    connect_timeout = query.get('connect_timeout', [None])[0]
    if connect_timeout:
        options['connect_timeout'] = int(connect_timeout)
    if options:
        config['OPTIONS'] = options

    return config

# Detectar rama actual y cargar archivo .env correspondiente
def get_current_branch():
    try:
        branch_file = BASE_DIR.parent / '.git' / 'HEAD'
        if branch_file.exists():
            content = branch_file.read_text().strip()
            if 'ref: refs/heads/' in content:
                return content.split('ref: refs/heads/')[-1]
    except Exception:
        pass
    return 'master'  # Default a master/producción

CURRENT_BRANCH = get_current_branch()

# Determinar qué archivo .env usar según la rama
if CURRENT_BRANCH == 'develop':
    env_file = BASE_DIR / '.env.staging'
else:
    env_file = BASE_DIR / '.env.production'

# Fallback a .env genérico si no existe el archivo específico
if not env_file.exists():
    env_file = BASE_DIR / '.env'

# Cargar variables de entorno desde el archivo .env apropiado
if env_file.exists():
    for raw_line in env_file.read_text(encoding='utf-8').splitlines():
        line = raw_line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue
        key, value = line.split('=', 1)
        os.environ.setdefault(key.strip(), value.strip())


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_to_bool(os.getenv('DJANGO_DEBUG'), default=False)

# SECURITY WARNING: keep the secret key used in production secret!
# Permitir tanto DJANGO_SECRET_KEY como SECRET_KEY para compatibilidad.
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY') or os.getenv('SECRET_KEY')
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'django-insecure-local-dev-only'
    else:
        raise RuntimeError('Falta configurar DJANGO_SECRET_KEY o SECRET_KEY para ejecutar Django con DEBUG=False.')

# Hosts permitidos por Django; configurable por entorno.
allowed_hosts_default = 'localhost,127.0.0.1' if DEBUG else ''
ALLOWED_HOSTS = _split_csv_env(os.getenv('DJANGO_ALLOWED_HOSTS', allowed_hosts_default))


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'cloudinary_storage',
    'cloudinary',
    'excursiones',
    'playas',
    'ofertas',
    'estados',
    'contacto',
]


MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'estados.middleware.EstadoExpirySyncMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

database_url = os.getenv('DATABASE_URL', '').strip()
if database_url:
    default_database = _build_database_config_from_url(database_url)
else:
    default_database = _build_sqlite_database_config()

default_database['CONN_MAX_AGE'] = int(os.getenv('DATABASE_CONN_MAX_AGE', '60'))
DATABASES = {
    'default': default_database,
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Configuración de Cloudinary desde variables de entorno
cloudinary.config(
    cloud_name=os.getenv('CLOUDINARY_CLOUD_NAME'),
    api_key=os.getenv('CLOUDINARY_API_KEY'),
    api_secret=os.getenv('CLOUDINARY_API_SECRET')
)

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS para permitir frontend local/deploy hablar con la API.
cors_origins_default = 'http://localhost:5173,http://127.0.0.1:5173,http://localhost:5175,http://127.0.0.1:5175' if DEBUG else ''
CORS_ALLOWED_ORIGINS = _split_csv_env(
    os.getenv('DJANGO_CORS_ALLOWED_ORIGINS', cors_origins_default)
)
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_METHODS = [
    "GET",
    "POST",
    "PATCH",
    "PUT",
    "DELETE",
    "OPTIONS",
]
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]
CORS_EXPOSE_HEADERS = [
    'access-control-allow-credentials',
    'content-type',
    'authorization',
]

csrf_trusted_origins_default = ','.join(CORS_ALLOWED_ORIGINS) if DEBUG else ''
CSRF_TRUSTED_ORIGINS = _split_csv_env(
    os.getenv('DJANGO_CSRF_TRUSTED_ORIGINS', csrf_trusted_origins_default)
)

# Seguridad base DRF: lectura publica, escritura autenticada.
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'backend.authentication.AdminTokenAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
}

ADMIN_TOKEN_MAX_AGE_SECONDS = int(os.getenv('ADMIN_TOKEN_MAX_AGE_SECONDS', '28800'))

# Email para el formulario de contacto.
# En producción usa SMTP real; en desarrollo, si faltan credenciales, se mantiene la salida por consola.
EMAIL_HOST = os.getenv('EMAIL_HOST', '')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = _env_to_bool(os.getenv('EMAIL_USE_TLS', 'True'))
EMAIL_USE_SSL = _env_to_bool(os.getenv('EMAIL_USE_SSL', 'False'))
EMAIL_TIMEOUT = int(os.getenv('EMAIL_TIMEOUT', '20'))
DEFAULT_FROM_EMAIL = os.getenv(
    'DEFAULT_FROM_EMAIL',
    EMAIL_HOST_USER or 'info@vicenteviajes.com',
)
CONTACT_RECIPIENT_EMAIL = os.getenv('CONTACT_RECIPIENT_EMAIL', 'info@vicenteviajes.com')
CONTACT_EMAIL_LOGO_URL = os.getenv('CONTACT_EMAIL_LOGO_URL', '')
CONTACT_EMAIL_PROVIDER = os.getenv('CONTACT_EMAIL_PROVIDER', 'django').strip().lower()
CONTACT_EMAIL_ASYNC = _env_to_bool(os.getenv('CONTACT_EMAIL_ASYNC'), default=True)
RESEND_API_KEY = os.getenv('RESEND_API_KEY', '').strip()
RESEND_FROM_EMAIL = os.getenv('RESEND_FROM_EMAIL', DEFAULT_FROM_EMAIL).strip()

# Anthropic / Claude
ANTHROPIC_API_KEY = os.getenv('ANTHROPIC_API_KEY', '').strip()

email_password_is_placeholder = EMAIL_HOST_PASSWORD.startswith('CAMBIA_')

if EMAIL_HOST and EMAIL_HOST_USER and EMAIL_HOST_PASSWORD and not email_password_is_placeholder:
    EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
else:
    # Fallback para desarrollo local si faltan credenciales SMTP
    EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')

# Configuración de Cloudinary para almacenamiento de imágenes
import cloudinary
import cloudinary.uploader
import cloudinary.api

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.getenv('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': os.getenv('CLOUDINARY_API_KEY'),
    'API_SECRET': os.getenv('CLOUDINARY_API_SECRET'),
}

cloudinary.config(**CLOUDINARY_STORAGE)

# Usar Cloudinary como backend de almacenamiento por defecto para archivos media
DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
