# Generated by Django 6.0.3 on 2026-03-31 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='image',
            field=models.FileField(upload_to='estados/'),
        ),
        migrations.CreateModel(
            name='EstadoConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autoplay_ms', models.PositiveIntegerField(default=3200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
