# Generated by Django 6.0.3 on 2026-03-31 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estados', '0002_alter_estado_image_estadoconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='estado',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='estado',
            name='excursion_date',
            field=models.DateField(default='2099-12-31'),
            preserve_default=False,
        ),
        migrations.AlterModelOptions(
            name='estado',
            options={'ordering': ['excursion_date', 'display_order', '-created_at']},
        ),
    ]
