# Generated by Django 6.0.3 on 2026-04-16 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estados', '0003_estado_subtitle_estado_excursion_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Vicente Viajes/estados/'),
        ),
    ]
