# Generated by Django 6.0.3 on 2026-04-16 21:59

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estados', '0003_estado_subtitle_estado_excursion_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
