# Generated by Django 6.0.3 on 2026-05-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estados', '0004_alter_estado_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Vicente Viajes/estados/'),
        ),
    ]
