# Generated by Django 6.0.3 on 2026-04-16 21:59

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playas', '0004_playa_characteristics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playa',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
