# Generated by Django 6.0.3 on 2026-05-11 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playas', '0005_alter_playa_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playa',
            options={'ordering': ['-departure_date', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='playa',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='playa',
            name='rating',
        ),
        migrations.AddField(
            model_name='playa',
            name='departure_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playa',
            name='departure_info',
            field=models.TextField(blank=True, help_text='Puntos de salida con horarios, uno por línea'),
        ),
        migrations.AddField(
            model_name='playa',
            name='includes',
            field=models.TextField(blank=True, help_text='Qué incluye (separado por líneas)'),
        ),
        migrations.AddField(
            model_name='playa',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playa',
            name='month',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='playa',
            name='not_includes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='playa',
            name='price_child',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio niños/as 2-11 años, mayores de 65 y personas con discapacidad', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='playa',
            name='return_time',
            field=models.CharField(blank=True, help_text='Hora de regreso, p.ej. 23:59', max_length=20),
        ),
    ]
