# Generated by Django 6.0.3 on 2026-05-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playas', '0006_update_playa_fields_for_beach_trips'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playa',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Vicente Viajes/playas/'),
        ),
    ]
