# Generated by Django 6.0.3 on 2026-04-16 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0003_add_display_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oferta',
            options={'ordering': ['display_order', '-created_at']},
        ),
        migrations.AlterField(
            model_name='oferta',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Vicente Viajes/ofertas/'),
        ),
    ]
