# Generated by Django 6.0.3 on 2026-04-16 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0003_add_display_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oferta',
            options={'ordering': ['display_order', '-created_at']},
        ),
    ]
