# Generated by Django 6.0.3 on 2026-04-16 21:59

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0003_add_display_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oferta',
            options={'ordering': ['display_order', '-created_at']},
        ),
        migrations.AlterField(
            model_name='oferta',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
