# Generated by Django's makemigrations --merge
from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ("ofertas", "0004_alter_oferta_options"),
        ("ofertas", "0004_alter_oferta_options_alter_oferta_image"),
    ]

    operations = [
    ]
