# Generated by Django 6.0.3 on 2026-05-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0008_fix_legacy_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='departure_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oferta',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='oferta',
            name='includes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='oferta',
            name='not_includes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='discount',
            field=models.CharField(default='0%', max_length=20),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Vicente Viajes/ofertas/'),
        ),
    ]
